### ISSUE TITLE
QT5 build

### ISSUE THREAD

**Issue by lamskoy** [psi-plus/plugins#13]
Building in ArchLinux from AUR. Modified PKGBUILD for QT5 support.
Getting error:

> g++ -c -pipe -O2 -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -std=gnu++0x -Wall -W -D_REENTRANT -fPIC -DQT_NO_DEBUG -DQT_PLUGIN -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_XML_LIB -DQT_CORE_LIB -I. -I.ui -isystem /usr/include/psi-plus/plugins -isystem /usr/include/qt -isystem /usr/include/qt/QtWidgets -isystem /usr/include/qt/QtGui -isystem /usr/include/qt/QtXml -isystem /usr/include/qt/QtCore -I.moc -I.ui -I/usr/lib/qt/mkspecs/linux-g++ -o .obj/attentionplugin.o attentionplugin.cpp
> 
> In file included from /usr/include/qt/QtCore/qchar.h:37:0,
>                  from /usr/include/qt/QtCore/qstring.h:41,
>                  from /usr/include/qt/QtCore/qdir.h:37,
>                  from /usr/include/qt/QtWidgets/qfiledialog.h:37,
>                  from /usr/include/qt/QtWidgets/QFileDialog:1,
>                  from attentionplugin.cpp:21:
> attentionplugin.cpp:147:1: error: static assertion failed: Old plugin system used
>  Q_EXPORT_PLUGIN(AttentionPlugin);
> 
>  ^
> Makefile:436: recipe for target '.obj/attentionplugin.o' failed

**Comment by lamskoy** [comment]
Was able to build psi-plus-git package from AUR with QT5 btw - works good

**Comment by lamskoy** [comment]
Not sure this solution will work:
http://stackoverflow.com/questions/22394477/how-to-create-plugins-qt-5-2-0

**Comment by lamskoy** [comment]
[psi-plus-plugins-git-0.15.467-1.src.tar.gz](https://github.com/psi-plus/plugins/files/202389/psi-plus-plugins-git-0.15.467-1.src.tar.gz)
[psi-plus-git-0.16.543-1.src.tar.gz](https://github.com/psi-plus/plugins/files/202390/psi-plus-git-0.16.543-1.src.tar.gz)
Attached my modified PKGBUILDs

**Comment by Vitozz** [comment]
Your plugins psi-plus-plugins-git-0.15.467-1.src.tar.gz are old. Try to use git repository sources to build plugins. All plugins are compiled without any problems with qt5.

**Comment by lamskoy** [comment]
@Vitozz Sources are up-to-date. It just takes 0.15.467 from git tags

> $ git describe --tags | cut -d - -f 1-2 --output-delimiter=.
> 0.15.467
> 

Found what happens. HAVE_QT5 is not set. Preprocessor fails coz:
> #ifdef HAVE_QT5 
is not processed

**Comment by lamskoy** [comment]
ok now all fine
DEFINES += HAVE_QT5 
fixed build
