### ISSUE TITLE
Плагин для "быстрых сообщений"

### ISSUE THREAD

**Issue by SergeyShorin** [psi-plus/plugins#14]
Приветствую всех!
Планируется ли написание плагина "Быстрые сообщения"
Функционал:
в настройках плагина пользователь создаёт набор быстрых сообщений либо как набор строк (т.е. однострочные сообщения), либо как "Заголовок - тело" (в этом случае в теле можно предусмотреть форматирование)
в окне чата создаётся кнопка "быстрый ответ" или "шаблоны" или ещё как-нить...
после нажатия на кнопку в окне чата появляется pop-up меню, и пользователь выбирает сообщение, которое вставится в ... ... ...
в настройках указывается что делать с этим сообщением - либо сразу отправляется собеседнику, либо вставляется в поле ввода сообщения (т.е. пользователь сможет отредактировать текст, и должен будет сам его отправить).

**Comment by wadealer** [comment]
Этот функционал встроен в кору. Называется Шаблоны сообщений. Есть кнопка на тулбаре чата, есть в контекстном меню на кнопке отправить.
