### ISSUE TITLE
Image Plugin doesn't work in Group Chat

### ISSUE THREAD

**Issue by klou** [psi-plus/plugins#18]
The XML string is the same as a standard "chat", but is not rendered in GroupChat windows.  Only "Image ##### bytes received"

**Comment by wadealer** [comment]
You should enable xhtml support for group chats. You can do this with
extended options plugin.

04 Фев 2017 г. 0:40 пользователь "Kris Lou" <notifications@github.com>
написал:

**Comment by klou** [comment]
Thanks!

This is also ```options.html.muc.render = true```.
